### ISSUE TITLE
Kanban board Set Up

### ISSUE THREAD

**Issue by eapenzacharias** [eapenzacharias/Startrek#21]
https://github.com/eapenzacharias/Startrek/projects

We are a two-member team
### Team:

- @JasemDuncan 
- @eapenzacharias

**Comment by o-rashad** [comment]
Asslam Alaikum team @eapenzacharias @JasemDuncan  ,😊

Hi👋🏽

Your project is complete

Good luck with the upcoming milestones :muscle:  

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
