### ISSUE TITLE
Peer to peer Code Review - 11/25

### ISSUE THREAD

**Issue by lu-jim** [eapenzacharias/Startrek#30]
@eapenzacharias  and @JasemDuncan!

This is looking like a good project so far. There are a few small things to consider in the future:
## I like 👍 
- Good looking UI for the home
- Great use of local storage to improve responsiveness.
## To consider 🤔 
- Please check that the modal has a close button and that if the user clicks outside, it will also close.
- When generating the modal, consider creating one node( E.G.`div`) and then completing the entire code replacing the `innerHTML` property instead of creating a node for each element of the object.

**Comment by eapenzacharias** [comment]
Thank you for the comments. We are working on it
